### ISSUE TITLE
[BUG] images are being removed when modifying an instrument and not uploading a new image

### ISSUE THREAD

**Issue by Willdogx** [PaulaMogon/php101#20]
If you create an instrument with an image, and then you go to the modify form of that instrument, you will see the image.
If you make a modification, like the name, the price, or the stock, but you don't upload a new image, the image is lost. If you go to modify form for that instrument again, you won't see an image.

**Comment by PaulaMogon** [comment]
I have not done it yet.
What I know: 
- when modifying an instrument: if a new image is not uploaded, the previous loaded image is lost
- db does bring the image's route as it is stored (128_guitar.jpg)
- if it is uploaded, it just keeps the $instrumentId_ route (128_) and the other part is lost
- $imageFilename = $instrumentId . '_' . $_FILES['image']['name'];
Why: 
- good question
When: 
- when the modify instrument form is updated and no image has been selected
Where: 
- modify instrument form (might be on modify instrument too)

**Comment by PaulaMogon** [comment]
Done.
