### ISSUE TITLE
Create a new 'instruments' section in the page

### ISSUE THREAD

**Issue by Willdogx** [PaulaMogon/php101#6]
Create a new page called instrumentsList.php which displays a table with the name of each instrument, the price, and the quantity in stock. Add a link to that page on the header.

To do so Create a new database table called instrumens with the following columns:
* An ID, an int with auto-increment and primary key.
* name, varchar of 100 characters
* price, a double
* stock, an int

**Comment by PaulaMogon** [comment]
¡Homework done, che! :)
