### ISSUE TITLE
Create instrument page

### ISSUE THREAD

**Issue by Willdogx** [PaulaMogon/php101#7]
Put a "New Instrument" button above the table in "list instruments" that can only be seen if the user is logged in.
This button takes the user to an instrument creation form. The inputs can not be left empty, so they must be validated and show an error if any of them is missing (except the ID, which is not even shown in the form since its autoincrement).
After the creation of the instrument, the user should be redirected to the instruments list again.
Remember to also check that the user is logged  in in the creation form

**Comment by PaulaMogon** [comment]
Halo! **SOS** con los errores! Estoy comparando con el de ''registerForm.php'', pero ahí no funcionan los errores (cuestión que también he de revisar) y con el ''loginForm.php'', pero en este caso identifica los errores desde el inicio de sesión (if (empty($_SESSION['userError'])). No obstante, sí registra el nuevo instrumento en la lista y tras ser registrado, sí redirige a la lista de instrumentos :) 
(La próxima vez interactúo en inglés, me di cuenta a medio párrafo)
