### ISSUE TITLE
Create update instrument page

### ISSUE THREAD

**Issue by Willdogx** [PaulaMogon/php101#8]
In the instruments list, if the user is logged in, show a button "Update" in each row that takes the user to a update form, with each field(except the Id) prefilled with the data from the database. Validate each field so that none is left empty and after the update redirect the user back to the instruments list.

**Comment by PaulaMogon** [comment]
Button included. Error on each field. I have checked the code on modifyUserForm.php & modifyUser.php and tried to do the same but adapting it. It does not work and the worst thing is that I do not know where the error come from :( 
<img width="669" alt="error" src="https://user-images.githubusercontent.com/74676845/105627947-27932180-5e3a-11eb-82d5-914e0f1e6eb8.png">
