### ISSUE TITLE
Delete instrument button

### ISSUE THREAD

**Issue by Willdogx** [PaulaMogon/php101#9]
If the user is logged in, show a "Delete" button in each row of the instruments list. After deletion redirect the user to the instruments list again.

**Comment by PaulaMogon** [comment]
I think I am having the same issue than on the ticket to modify an instrument: ''$_GET['instrumentId']''. The instrument is not deleted.

**Comment by PaulaMogon** [comment]
Conseguí que se borren cambiando a: $_GET['id']           :)
